### ISSUE TITLE
Support for <PackageReference />

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#116]
VS15 will better support NuGet references. Here is some information: https://blogs.msdn.microsoft.com/dotnet/2016/10/19/net-core-tooling-in-visual-studio-15/

As of now, NuGet are resolved by Paket and post-processed by fullbuild (custom target generation to reference package assemblies). This is not bad because Paket.lock allows one to understand what's happening.

Using <PackageReference /> this could remove identifying explicitly assembly references. Which could be nice.

So what ?

**Comment by baronfel** [comment]
You may want to check the paket 4 alphas, where Steffan has done initial work to support PackageReference in Paket

**Comment by pchalamet** [comment]
full-build uses Paket underneath but in a sandbox way: paket is not allowed to modified projects, because modifying projects is not the way to go. Instead, full-build create indirection for packages and projects at a global level.

full-build is about knowing projects structure and how to optimize the build and let developers deal with a lot of projects (switching from binary to sources and vis-versa and enabling partial build in CI while retaining global consistency).

The question here is: does it worth the game to use PackageReference instead of Reference on packages assemblies ?

**Comment by pchalamet** [comment]
Support for PackageReference added to v3.1
