### ISSUE TITLE
Baseline should be stored alongside binaries not using a tag on all repositories

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#163]
Baseline could be implemented using only a tag on master repository (aka .full-build) and a baseline file in artifact binaries.

This would prevent polluting repositories with useless tags. Only tag on master is really important.

**Comment by pchalamet** [comment]
review from your working branch @sergii-s

src/FullBuild/Commands/Workspace.fs
pullMatchingBinaries -> pullLatestBinaries

I do not agree as this is really matching binaries that is expected - not latest.
This is really important to checkout whole workspace to a specific version *and* get matching binaries.

**Comment by pchalamet** [comment]
@sergii-s: I have a doubt... shall we keep the tag on the master repository or not ?

I do not think it's technically required anymore (as far as I recall, even for branches). If not required, this means some code could be trashed away in Vcs (tagging & find tag) :-)

**Comment by pchalamet** [comment]
Nahh.. just forget it. We still need to tag to get matching binaries.

**Comment by pchalamet** [comment]
But it worth trying to get rid of this in the future - it's mostly noise.

**Comment by sergii-s** [comment]
implemented in 4.2
Main repo is still tagged though
