### ISSUE TITLE
Remove specific Gerrit clone feature

### ISSUE THREAD

**Issue by cboudereau** [full-build/full-build#167]
The specific gerrit clone cause a bug on the copy of the commit-msg. Gerrit offered a clone with hook message feature that we have to use instead.

Here is the error message of the build output : Could not find a part of the path 'd:\builds\master\workspace\*******\.git\hooks\commit-msg'.

May be remove the specific gerrit clone and do not copy the commit-msg by using a custom git alias command to clone with hook message.

**Comment by pchalamet** [comment]
There is not even a single question here...

What's the point here frankly ?
Is there any problem ? Which version ?
Have you tried to investigate before ? Can you offer a repro ?
Have you read first Gerrit manual ? Do you know what scp is ?

What's the point of your PR ? It just removes useful feature without providing any constructive answer ?
