### ISSUE TITLE
"Branch" command is pulling binaries

### ISSUE THREAD

**Issue by sergii-s** [full-build/full-build#168]
Pulling binaries probably shouldn't be a part of branch command.

Potential problem scenario : 
"Full" build of the specific branch
If the build is "full" then old binaries shouldn't be pulled at all because it could lead to irrelevant build result.

The 100%-problem scenario is when deleting the repository/project from the anthology.
What will happen after "branch" command : old binaries(+anthology) pulled and "doctor" command fails because unable to find repo/project

Proposition:
Pull --bin command should be separeted from "branch" command

**Comment by pchalamet** [comment]
Yeah that has been done to get matching binaries automatically. This is same as checkout or branch. It does make sense indeed to avoid messing around the workspace.

I do not really get the remove repository/project action. Could you elaborate ? That could be a bug in anthology rebuilding. Just give the complete list of commands to reproduce this. Thanks !

**Comment by sergii-s** [comment]
I mean when the project was deleted from the repository or when the repository was completely deleted from the globals file.
In this case "branch" command will pull anthology with deleted project and "doctor" will fail.
And even if doctor not fails the new anthology will still contain the deleted repository.
Had the same problem once when renamed one artifact.

To reproduce -> 
On the branch build delete the repository from the globals and try to rebuild.
If build script contains doctor command it will allways fails
If build script doesn't contain doctor command then the build output will allways have deleted repository content(dll-s and in .anthology)

You can test as well on the master branch but the build script should be:
fullbuild branch master
fullbuild doctor
fullbuild view all */*
fullbuild build all

**Comment by pchalamet** [comment]
Well.. ok I see.
The fact branch does not pull is probably the problem too (because source is not in sync with binaries - leading to aforementioned problem I guess).

This is not completely broken, but before avoiding pulling binaries, this would be nice first to fix the branch command and ensuring it pulls after checkout. But this could fail too btw if some work has been done locally and not pushed (ie: shared branch). If everything is ok, we can safely assume sources (hence .anthology's) and binaries are in line.

**Comment by pchalamet** [comment]
Probably link this to #161 too

**Comment by sergii-s** [comment]
How is #186 related? it is totally oposit

**Comment by sergii-s** [comment]
Solved with --src option of the branch command
