### ISSUE TITLE
convert messes up the import targets order in csproj

### ISSUE THREAD

**Issue by blew** [full-build/full-build#170]
When using fb convert on a web application, the order and location of the <import ...targets> tags get messed up and the build process doesn't generate a [bin]  folder in the root of the web-application's destination zip folder.
before converting (this does generate a [bin] folder:
[before convert.txt](https://github.com/full-build/full-build/files/1165956/before.convert.txt)
after converting:
[after convert.txt](https://github.com/full-build/full-build/files/1165957/after.convert.txt)

**Comment by pchalamet** [comment]
Not that much "messed up"... F# and asp.net builds are completely broken and brittle.
try 4.1.664 then.
