### ISSUE TITLE
Extensible publish process

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#175]
Packaging everything on publish process is not sufficient for some applications.

For web projects, we could have some more extra steps:
* minify
* precompile

Same applies for standard .net application where pre-jitting could be interesting.

To say the least, publish process is too limited after "copy" step and extensibility must be introduced.
One way to do that would be to call a script, fake or whatever that could help customizing this.

Another way would be to just do nothing, copy output just prepares everything - allowing for custom transformation then.

**Comment by sergii-s** [comment]
I think we can do both. The first solution it's faster and easier for user, the second have less dependenices on full-build.

For the first solution it could be extension of the "add application" command with custom script :
"fullbuild add application myPublisher.bat myApp myProject"
"fullbuild add application myPublisher.fs myApp myProject"
"fullbuild add application myPublisher.exe myApp myProject"

For the second we should provide some helper comands to detect affected repositories during the incremental build,

User will have the possibility to choose either to integrate his scripts into the full-build either to do it on his own in the global build script
