### ISSUE TITLE
Add support for dacpac

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#180]
dacpac projects (SQL Server projects - *.sqlproj) are not correctly handled. 

What does not work as of now:
* searching for *.sqlproj
* correctly detect dacpac output name (<SqlTargetName />)
* OutputType is Database
* dacpac reference (aka ProjectReference in mbuild world) will lose some attributes (SuppressMissingDependenciesErrors for eg)

Note that there are 2 artifacts generated when building such projects: a dacpac and an assembly (sqlclr stuff).

TODO:
- [x] search for *sqlproj
- [x] detect dacpac output name (SqlTargetName)
- [x] handle Database OutputType
- [x] handle sqlclr assembly (see copy file in fb.targets)
- [x] generate ArtifactReference instead of Reference in target files

Left for later:
- [ ] preserve reference attributes

**Comment by sergii-s** [comment]
Good idea, real requirement?

**Comment by pchalamet** [comment]
Yes:
* you can mix .net and dapac in one repository with projectreference (sqlclr) - this means build is incomplete as fb completly ignore such projects
* dacpac can reference other dacpacs
* building time can be quite huge

**Comment by pchalamet** [comment]
Moreover it should be quite easy to add support.

Still have a mixed feeling about project reference attributes - feels like something is overlooked - this could impact binary reference. Have to validate this first.

**Comment by pchalamet** [comment]
It's ok for reference attributes - they can be preserved across project reference or reference.

It's no big deal not to have them at first (this control warnings level) but could be nice to support this in mid term. Those kind of attributes have already been seen with Paket (<Paket>true</Paket>) but it was not a strong requirement to round trip back to Paket at the time :-)

I will create another issue to track this more specifically.

**Comment by pchalamet** [comment]
Oups did not check it right:

```
    <ArtifactReference Include="..\other-dacpac\bin\Debug\other-dacpac.dacpac">
      <HintPath>..\other-dacpac\bin\Debug\other-dacpac.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
    </ArtifactReference>

```

It's ArtifactReference and *not* Reference. Not a big deal indeed but have to take care of project type to generate correct reference.

**Comment by pchalamet** [comment]
Done
