### ISSUE TITLE
Update dev cycle workflow

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#181]
Gitflow is not used anymore - get rid of this and update contributing guidelines.

Then we publish nuget package a little bit too often. Sometimes just a refactoring - and this is useless.

Master shall be green with tests passing. This does not mean we want to release.

Proposition:
* patch applies to master (next release) - fast-forward + PR  validated
* apply a tag to publish nuget. But frankly I do not want to spend long time thinking about the version management. Using another build in appveyor could solve this problem just to publish the nuget in master build.

TODO:
- [x] Remove NuGet push from appveyor  - use deployment interface from AppVeyor
- [x] master branch generates stable nuget
- [x] beta/* branches generate beta nuget
- [x] all other branches generate alpha nuget

**Comment by sergii-s** [comment]
👍

**Comment by pchalamet** [comment]
done
