### ISSUE TITLE
Deprecate upgrade command

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#184]
It's great but we we have a total of 3 deployments options as of now:
* NuGet
* GitHub/release
* upgrade

Would be better to favor NuGet - so much easier to bootstrap and upgrade.

TODO:
- [ ] remove upgrade command
- [ ] remove all releases from GitHub (see https://github.com/stevemao/github-remove-all-releases)
- [ ] register system extension with custom command (install)

**Comment by sergii-s** [comment]
We could just modify upgrade command in order to use nuget packages and not github release. 
Like that we still have the possibility to "customize" upgrade process with system extentions and maybe other steps

**Comment by sergii-s** [comment]
But after looking #33 this would simplify server install.

**Comment by pchalamet** [comment]
Yes we could still plug upgrade on NuGet - but is it useful ?
fb has not only dependencies on nunit & paket but also git, svn & msbuild. FB mostly requires "external" setup anyway and I do not really expect we will manage to mask all dependencies.

**Comment by sergii-s** [comment]
Ideally - Msbuild - nuget, git/svn - .net implementations so nugets as well, nunit/xunit/mstest - client dependencies

**Comment by pchalamet** [comment]
that's not realistic.
