### ISSUE TITLE
Correctly handle nuget dependencies (depend on targetFramework)

### ISSUE THREAD

**Issue by sergii-s** [full-build/full-build#195]
**Symptom :** 
The "convert" command removes (almost) all .net framework references from the .anthology if the nuget contains .netstandard reference.

**Root cause :** 
The nuget dependencies are not correctly handled. 

**Example :**
.nuspec for the CsvHelper package contains :
```xml
<dependencies>
      <group targetFramework=".NETFramework2.0" />
      <group targetFramework=".NETFramework3.5" />
      <group targetFramework=".NETFramework4.0" />
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETPortable4.0-Profile328" />
      <group targetFramework=".NETStandard1.3">
        <dependency id="NETStandard.Library" version="[1.6.0, )" />
        <dependency id="Microsoft.CSharp" version="[4.0.1, )" />
        <dependency id="System.Reflection.TypeExtensions" version="[4.1.0, )" />
      </group>
    </dependencies>
```

In this case we should take into account .net standard library only for projects that targets .netstandard1.3

**Comment by pchalamet** [comment]
That's the case I think. It's all in targets of the package. There is a link but won't be used normally.
Also, this is linked to "framework: XXX" in paket.dependencies.

**Comment by pchalamet** [comment]
Btw, I'm getting tired of managing packages this way (using targets & Reference). It has a lot of subtleties and shall be definitively managed by MsBuild.

It's time for a v5 using PackageReference only and publish as NuGet... :-) MsBuild has it right now + autogenerate binding redirect.

**Comment by sergii-s** [comment]
https://github.com/dotnet/announcements/issues/31

**Comment by sergii-s** [comment]
> Shall be handled correctly I guess. It's all managed in the targets of the package. There is an import but won't be used normally.

I think it's correctly handled in the "package.targets" import, but not in the "convert" function as it removes .net framework assembly references from the anthology

**Comment by sergii-s** [comment]
[I think it's here](https://github.com/full-build/full-build/search?utf8=%E2%9C%93&q=RemoveAssembliesFromPackagesOrProjects&type=)

**Comment by pchalamet** [comment]
Ha yes.. maybe after all. Can't remember. This has to be investigated if you feel so.

**Comment by pchalamet** [comment]
That's probably why it's a good reason to move to PackageReference and stop doing this.

I guess the right fix would be to stop managing packages in full-build. Since https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection works correctly now, this would avoid a bunch of problems like this.

**Comment by sergii-s** [comment]
Agree on switching to PackageReference, but need a quick fix. 
Currently cannot use "convert" command.
I think we dont need the "RemoveAssembliesFromPackagesOrProjects" logic, it was probably used before introducing the "package.targets" or in the migration process, when some binary-references were tranformed to nuget-references.
Are there another usecases? What do you think about this?

**Comment by sergii-s** [comment]
Ok I got it, it is used while converting to remove assembly references of nuget-referenced dlls.
So should to be fixed to take into account the project's TargetFrameworkIdentifier and TargetFrameworkVersion while converting

**Comment by pchalamet** [comment]
But this will be painful - this is not the place to do that.
Targets are used to do this - take into account the build context and inject the dependencies. This is basically what PackageReference does alongside Sdk import.

Yes RemoveAssembliesFromPackagesOrProjects is used to remove from reference assemblies from a packages - there can be some leftover from NuGet and it's good to remove them.
But it's usually not a big deal if package import correctly its dependency on other packages.

Normally, you should have in CsvHelper package.targets following imports:
* NETStandard.Library
* Microsoft.CSharp
* System.Reflection.TypeExtensions

No ?

**Comment by pchalamet** [comment]
Just generated package import for CsvHelper and got this:

```
  <Import Project="$(SolutionDir)\.full-build\packages\microsoft.csharp/package.targets" Condition="'$(FullBuild_microsoft_csharp_Pkg)' == ''" />
  <Import Project="$(SolutionDir)\.full-build\packages\netstandard.library/package.targets" Condition="'$(FullBuild_netstandard_library_Pkg)' == ''" />
  <Import Project="$(SolutionDir)\.full-build\packages\system.reflection.typeextensions/package.targets" Condition="'$(FullBuild_system_reflection_typeextensions_Pkg)' == ''" />
  <Choose>
    <When Condition="$(TargetFrameworkIdentifier) == '.NETFramework' And ($(TargetFrameworkVersion) == 'v2.0' Or $(TargetFrameworkVersion) == 'v3.0')">
      <ItemGroup>
        <Reference Include="CsvHelper">
```

So dependencies are correctly imported. The wrong thing is that those 3 packages are unconditionally imported - which is plain wrong. They should be imported if and only if a .NETStandard1.3 build is taking place.

Should be quiet easy to fix in package target file generator.

**Comment by pchalamet** [comment]
I've implemented qa tests in branch `feature/fix-convert-with-platforms` using CsvHelper package.
Unfortunately, I can't understand what you expect.
@blew can you convert this project and tell me what you expect please ?
* cd qa/qa-frameworks
* ..\..\refbin\fullbuild.exe convert *
* check framework/framework.csproj

Just tell me what you expect - because as of now, system assemblies are still there.

**Comment by pchalamet** [comment]
Fixed in master. The bug was elsewhere: assemblies scanning for packages was scanning the wrong folder: assemblies from other folders than lib was found - and that's no good at all.

@sergii-s @blew: can you test the latest version in master please ?
