### ISSUE TITLE
Use type provider to patch projects

### ISSUE THREAD

**Issue by pchalamet** [full-build/full-build#36]
Maintenance will be easier.

**Comment by cboudereau** [comment]
Hello, I have done this kind of tasks before. But the *sproj format is a metamodel. When the type provider supply the type you will have to wrap the metamodel into lots of functions. Metamodel is not a good candidate with type provider. Here is the code of my experience with msbuild projet and type provider : https://github.com/cboudereau/DependencyWalker/blob/master/DependencyWalker/DependencyWalker.fsx

**Comment by pchalamet** [comment]
Just submit a PR to make this go forward please.

**Comment by pchalamet** [comment]
won't do.
