### ISSUE TITLE
Create test repositories for learning, developing and testing fullbuild

### ISSUE THREAD

**Issue by blackhill** [full-build/full-build#83]
In order to learn, dev and test full-build it would be nice to have some "test repositories" with predefined dependencies available in https://github.com/full-build

For example:
- xproj (repository)
  --> csproj (dependency)
- csproj (repository)
  --> vbproj (dependency)
  --> fsproj (dependency)
- vbproj (repository)
- fsproj (repository)

**Proposed naming conventions for repositories**
- full-build.learn.{projectExtension}

Example:
- full-build.learn.csproj for .csproj repository
- full-build.learn.fsproj for .fsproj repository
- full-build.learn.fullbuild for the fullbuild repository

Nuget package project dependency will be store in nuget.org gallery.
The name will be the following : full-build.learn.{projectType}

**Comment by pchalamet** [comment]
qa repository mostly provides this.
